# Generated by Django 4.2.4 on 2023-08-29 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Место')),
                ('safety', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Безопасность')),
                ('calendar', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2001)], verbose_name='Календарь')),
                ('trip', models.PositiveIntegerField(verbose_name='Путешествие')),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'преимущество',
                'verbose_name_plural': 'преимущества',
                'ordering': ['-created_at'],
            },
        ),
    ]
