# Generated by Django 4.2.4 on 2023-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название миссии')),
                ('planned_date', models.DateField(verbose_name='Дата запуска')),
                ('price', models.PositiveIntegerField(verbose_name='Цена билета')),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'График полетов',
                'verbose_name_plural': 'Графики полетов',
                'ordering': ['planned_date'],
            },
        ),
    ]
