# Generated by Django 4.2.4 on 2023-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profits_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profits',
            name='calendar',
            field=models.CharField(max_length=64, verbose_name='Календарь'),
        ),
    ]
