# Generated by Django 4.2.4 on 2023-08-30 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profits_calendar_alter_profits_safety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profits',
            name='calendar',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Календарь'),
        ),
    ]
